routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('index');
});
*/
Route::get('/', [App\Http\Controllers\IndexController::class, 'index'])->name('index');

Route::get('/users', function () {
    return view('users');
});

Route::resource('paket','App\Http\Controllers\PaketController');

//Route::get('/paket/{id}', 'App\Http\Controllers\PaketController@show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/AmbilPaket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AmbilPaket extends Model
{
    use HasFactory;
}

app/Models/Log_Users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Log_Users extends Model
{
    use HasFactory;
}

app/Models/Paket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Paket extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use App\Models\Paket;
use App\Models\AmbilPaket;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth'); 
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $data = Paket::all();
        //$paket = AmbilPaket::where('id_user', Auth::id())->get();

        $paket = DB::table('ambil_pakets')
        ->join('pakets', 'ambil_pakets.idpaket', '=', 'pakets.idpaket')        
        ->select('ambil_pakets.*','pakets.*')
        ->where('ambil_pakets.id_user', Auth::id())
        ->get();

        return view('home', compact('data','paket'));        
    }
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Paket;

class IndexController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest'); 
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $data = Paket::all();
        return view('index', compact('data'));     
    }
}

app/Http/Controllers/PaketController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Paket;
use App\Models\AmbilPaket;

class PaketController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = 1;// Kategori::all();
        return view('paket.show', compact('data'));
    }

    public function show($id)
    {
        $paket = Paket::where('idpaket', $id)->get();
        return view('paket.show', compact('paket'));
    }

    public function store(Request $request)
    {
        /*
        $request->validate([
            'namakategori' => 'required',
        ]);
*/
        $ambilpaket = new AmbilPaket;

        $ambilpaket->idpaket = $request->idpaket;
        $ambilpaket->id_user = $request->user_id;
        $ambilpaket->tgljamdaftar = date('YmdHis');
        $ambilpaket->tglawal = date('Ymd');
        $ambilpaket->tglakhir = date('Ymd', strtotime(' + '.abs($request->durasi).' months'));
        $ambilpaket->statuspaket = 1;
        
        $ambilpaket->save();
/*
        $aktifitas = new Aktifitas;
        $aktifitas->tgljam = date('YmdHis');
        $aktifitas->nama_aktifitas = "Create Kategori";
        $aktifitas->deskripsi = $request->namakategori;
        $aktifitas->user_id = Auth::id();

        $aktifitas->save();

        Alert::success('Yeaaayy', 'Data kategori berhasil ditambahkan');
*/
    	return redirect('/home');
    }
}

resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Ask.Com - Forum Tanya Jawab</title> 
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <!--<link href="{{ asset('/adminlte/img/favicon.ico') }}" rel="icon">-->

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{ asset('/adminlte/lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/adminlte/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css') }}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ asset('/adminlte/css/bootstrap.min.css') }}" rel="stylesheet">
    @stack('style')

    <!-- Template Stylesheet -->
    <link href="{{ asset('/adminlte/css/style.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-red position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center" style="opacity:0.5; background-color:#666666">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Sidebar Start -->
        @include('adminlte.partial.sidebar') 
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            @include('adminlte.partial.navbar')
            <!-- Navbar End -->

			@yield('content')    
				
			<p>&nbsp;</p>
			<div align="center" style="position:fixed; bottom:0; font-weight:bold; width:inherit; background-color:#F3F6F9; border:thin solid #009CFF; border-left:none; border-right:none; border-bottom:none; color:#009CFF; font-size:12px; padding:5px;">
				Supported by SanberCode - Team 5
			</div>
			
        </div>
        <!-- Content End -->

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('/adminlte/lib/chart/chart.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/easing/easing.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/moment.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/moment-timezone.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js') }}"></script>
	
	<script src="{{ asset('/adminlte/js/main.js') }}"></script>

    @stack('scripts')
    @include('sweetalert::alert')
</body>

</html>

resources/views/adminlte/master2.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Membership - Web App</title> 
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <meta name="csrf-token" content="@yield('csrf-token')">

    <!-- Favicon -->
    <!--<link href="{{ asset('/adminlte/img/favicon.ico') }}" rel="icon">-->

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{{ asset('/adminlte/lib/owlcarousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/adminlte/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css') }}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{{ asset('/adminlte/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{{ asset('/adminlte/css/style.css') }}" rel="stylesheet">
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Content Start -->
        <div class="content open">
            

			@yield('content')    
        </div>
        <!-- Content End -->

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('/adminlte/lib/chart/chart.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/easing/easing.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/waypoints/waypoints.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/owlcarousel/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/moment.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/moment-timezone.min.js') }}"></script>
    <script src="{{ asset('/adminlte/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js') }}"></script>
	
	<script src="{{ asset('/adminlte/js/main.js') }}"></script>

    @stack('scripts')
</body>

</html>

resources/views/adminlte/partial/navbar.blade.php
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0"> 
                <a href="/" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary" style="margin:0; padding:0;"><i class="fa fa-hashtag me-2"></i>Membership.com</h3>
                </a>
                              
                <div class="navbar-nav align-items-center ms-auto">                  
                     <div class="d-flex ms-lg-4">
                            <a href="{{ route('logout') }}" class="btn btn-outline-primary" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>                         
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->

resources/views/adminlte/partial/navbar2.blade.php
<!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0"> 
                <a href="/" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary" style="margin:0; padding:0;"><i class="fa fa-hashtag me-2"></i>Membership.com</h3>
                </a>
                              
                <div class="navbar-nav align-items-center ms-auto">                  
                     <div class="d-flex ms-lg-4"><a class="btn btn-outline-primary" href="/login">Sign In</a><a class="btn btn-primary ms-3" href="/register">Sign Up</a></div>
                </div>
            </nav>
            <!-- Navbar End -->

resources/views/adminlte/partial/sidebar.blade.php
<!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3"> 
            <nav class="navbar bg-light navbar-light">
                <a href="#" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary" style="margin:0; padding:0;"><i class="fa fa-hashtag me-2"></i>ASK.COM</h3>
					<span style="font-size:12px; margin:0; padding:0; position:absolute; top:1; padding-left:30px">Forum Tanya Jawab</span>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4" style="margin-top:20px;">
                    <div class="position-relative">
                        @if (!Auth::user()->profile->avatar == null)
                            <img src="{{ asset('images/' . Auth::user()->profile->avatar) }}" alt="thumbnail_profile" class="rounded-circle" width="40px" height="40px">
                        @else
                            <img src="{{ asset('images/default-profile.png') }}" alt="thumbnail_profile" class="rounded-circle" width="40px" height="40px">            
                        @endif
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">{{Auth::user()->name}}</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="/admin" class="nav-item nav-link active"><i class="fa fa-home me-2"></i>Home</a>
                    <hr />
                    <a href="/kategori" class="nav-item nav-link"><i class="fa fa-book me-2"></i>My Category</a>
                    <a href="/tanya/create" class="nav-item nav-link"><i class="fa fa-paper-plane me-2"></i>Post Question</a>
					<hr />
                    <a href="/tanya" class="nav-item nav-link"><i class="fa fa-table me-2"></i>My Q & A</a>
                    <a href="/print-pdf" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>Reporting</a>
                   
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->

resources/views/home.blade.php
@extends('adminlte.master2') 

@section('content')
	<!-- Navbar Start -->
	@include('adminlte.partial.navbar')
	<!-- Navbar End -->
	
	<main class="main" id="top">
     
		<section class="pt-7">
			<div class="container">
			  <div class="row align-items-center">
				<div class="col-md-12 text-md-start text-center py-6">
				  <h1 class="mb-4 fs-9 fw-bold">Membership Web App</h1>
				  <p class="mb-6 lead text-secondary">Merupakan Sebuah Aplikasi Web untuk menjalankan sistem keanggotaan 
				  </p>
				</div>
				<div class="col-md-12" style="padding:50px" aling="center">
                @forelse ($paket as $key=>$value1)
                    <h2 class="mb-4 fs-9 fw-bold">Status Keanggotaan Kamu</h2>
                    <h2 class="mb-4 fs-9 fw-bold">Paket {{$value1->namapaket}}</h2>
                    <p class="mb-6 lead text-secondary"><b>Registrasi :</b> {{$value1->tglawal}}</p>
					<p class="mb-6 lead text-secondary"><b>Durasi :</b> {{$value1->durasi}} Bulan</p>
					<p class="mb-6 lead text-secondary"><b>Kadaluarsa :</b> {{$value1->tglakhir}}</p>
                @empty
					<h2 class="mb-4 fs-9 fw-bold">Pilih Paket Keanggotaan Kamu</h2>
					<div class="row align-items-center">
                    @forelse ($data as $key=>$value)
						<div class="col paketbox" >
							<h2 class="mb-4 fs-9 fw-bold">{{$value->namapaket}}</h2>
							<p class="mb-6 lead text-secondary"><b>Durasi :</b> {{$value->durasi}} Bulan</p>
							<p class="mb-6 lead text-secondary"><b>Harga :</b> Rp. {{number_format($value->harga)}}</p>				
							<div class="text-center"><a class="btn btn-warning" href="{{ route('paket.show', ['paket' => $value->idpaket] ) }}" role="button">Pilih Paket</a></div>											  			
						</div>
					@empty
						<div>Tidak ditemukan data</div>
					@endforelse  
					</div>
                @endforelse    
				</div>
			  </div>
			</div>
		  </section>
	</main>
		
@endsection

@push('scripts')
	<script>
	  
	</script>
@endpush

resources/views/index.blade.php
@extends('adminlte.master2') 

@section('content')
	<!-- Navbar Start -->
	@include('adminlte.partial.navbar2')
	<!-- Navbar End -->
	
	<main class="main" id="top">
     
		<section class="pt-7">
			<div class="container">
			  <div class="row align-items-center">
				<div class="col-md-12 text-md-start text-center py-6">
				  <h1 class="mb-4 fs-9 fw-bold">Membership Web App</h1>
				  <p class="mb-6 lead text-secondary">Merupakan Sebuah Aplikasi Web untuk menjalankan sistem keanggotaan 
				  </p>
				</div>
				<div class="col-md-12" style="padding:50px" aling="center">
					<h2 class="mb-4 fs-9 fw-bold">Pilih Paket Keanggotaan Kamu</h2>
					<div class="row align-items-center">
					@forelse ($data as $key=>$value)
						<div class="col paketbox" >
							<h2 class="mb-4 fs-9 fw-bold">{{$value->namapaket}}</h2>
							<p class="mb-6 lead text-secondary"><b>Durasi :</b> {{$value->durasi}} Bulan</p>
							<p class="mb-6 lead text-secondary"><b>Harga :</b> Rp. {{number_format($value->harga)}}</p>				
							<div class="text-center"><a class="btn btn-warning" href="/home" role="button">Pilih Paket</a></div>											  			
						</div>
					@empty
						<div>Tidak ditemukan data</div>
					@endforelse   
					</div>
				</div>
			  </div>
			</div>
		  </section>
	</main>
		
@endsection

@push('scripts')
	<script>
	  
	</script>
@endpush

resources/views/paket/index.blade.php
@extends('adminlte.master')

@section('content') 
	
	<div class="card-body">
		<div class="d-flex w-100 align-items-center justify-content-between">
			<a href="{{ route('kategori.create') }}" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Tambah</a>
			<h5>List Data Kategori</h5>
		</div>
		<hr/>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th style="width: 10px">#</th>
					<th>Nama Kategori</th>					
					<th style="width: 40px">Action</th>
				</tr>
			</thead>
			<tbody>
                    
            </tbody>
		</table>
	</div>
	
@endsection

@push('scripts')
	
@endpush

resources/views/paket/show.blade.php
@extends('adminlte.master2')

@section('content') 
	
	<div class="card-body">		
		<div class="d-flex w-100 align-items-center justify-content-between">
			<button type="button" class="btn btn-primary" onclick="document.location.href='{{ route('home') }}'"><i class="fa fa-arrow-circle-left"></i> Back</button>
			<a href="/" class="navbar-brand">
                <h3 class="text-primary" style="margin:0; padding:0;"><i class="fa fa-hashtag me-2"></i>Membership.com</h3>
            </a>
		</div>
		<hr/>

		<form action="{{ route('paket.index') }}" method="post">
		@csrf
		<div class="card-body">
			<div class="form-group">
				<input type="hidden" name="user_id" value="{{Auth::id()}}">
				<input type="hidden" name="idpaket" value="{{$paket[0]->idpaket}}">
				<input type="hidden" name="durasi" value="{{$paket[0]->durasi}}">
			</div>

			<h3>Paket Keanggotaan</h3><br>
			<h5>Nama Paket : {{$paket[0]->namapaket}}</h5>
			<h5>Harga : Rp. {{number_format($paket[0]->harga)}}</h5>
			<h5>Durasi : {{$paket[0]->durasi}} Bulan</h5>

			<h5>Tanggal Registrasi : {{date('Y-m-d')}}</h5>
			<h5>Tanggal Kadaluarsa : {{date('Y-m-d', strtotime(' + '.abs($paket[0]->durasi).' months'))}}</h5>
						
			</div>
			
			<div class="card-footer">
				<button type="submit" class="btn btn-warning">Daftar Sekarang</button>
			</div>
		</form>

		
	</div>
	
@endsection

@push('scripts')
	
@endpush